### ISSUE TITLE
SACSegmentationFromNormals to be implemented

### ISSUE THREAD

**Issue by vaibhavwalia921** [ADVRHumanoids/point_cloud2_filters#8]
Hello,

when I try to run the d435_example. I get the following error:
```

[pcl::SACSegmentation::initSACModel] No valid model given!
[pcl::SACSegmentation::segment] Error initializing the SAC model!
[pcl::SACSegmentation::initSACModel] No valid model given!
[pcl::SACSegmentation::segment] Error initializing the SAC model!
[pcl::SACSegmentation::initSACModel] No valid model given!
[pcl::SACSegmentation::segment] Error initializing the SAC model!
[pcl::SACSegmentation::initSACModel] No valid model given!
[pcl::SACSegmentation::segment] Error initializing the SAC model!
[pcl::SACSegmentation::initSACModel] No valid model given!
[pcl::SACSegmentation::segment] Error initializing the SAC model!
```
I have the same camera. I am using ubuntu 20.04 and ROS noetic. 
Following are my launch and config files:

```
<launch>
    <node pkg="sensor_filters" type="pointcloud2_filter_chain" output="screen" name="pointcloud2_filters">
        <remap from="~input" to="wrist_camera/depth/color/points" />
        <remap from="~output" to="/wrist_camera/depth/color/points/filtered" />
        <rosparam command="load" file="$(find point_cloud2_filters)/config/d435_example.yaml" />
    </node>
</launch>

```
```
output_queue_size: 10

cloud_filter_chain:
  - name: PassThroughFilter
    type: point_cloud2_filters/PassThroughFilterPointCloud2
    params:
      active: True
      input_frame: "wrist_camera_depth_optical_frame"
      output_frame: "wrist_camera_depth_optical_frame"
      keep_organized: True
      negative: False
      filter_field_name: "z"  # Focus on Z axis for height filtering
      filter_limit_min: 0.2   # Set minimum height (0.6 meters above ground or robot base)
      filter_limit_max: 4.0   # Set maximum height (approximately the table height)

      
  - name: CropBoxFilter
    type: point_cloud2_filters/CropBoxFilterPointCloud2
    params:          
      active: True
      input_frame: "wrist_camera_depth_optical_frame"
      output_frame: "wrist_camera_depth_optical_frame"
      keep_organized: True
      negative: False
      min_x: -2.0   # Set min X to cover the left side of the table (relative to the camera)
      max_x: 2.0    # Set max X to cover the right side of the table
      min_y: -1.0   # Set min Y to cover the front of the table (toward the camera)
      max_y: 0.4    # Set max Y to cover the back of the table
      min_z: 0.4   # Same Z bounds as PassThroughFilter to focus on the table height
      max_z: 5.0

      
  - name: VoxelGridFilter
    type: point_cloud2_filters/VoxelGridFilterPointCloud2
    params:
      active: true
      input_frame: "wrist_camera_depth_optical_frame"
      output_frame: "wrist_camera_depth_optical_frame"
      leaf_size_x: 0.1
      leaf_size_y: 0.2
      leaf_size_z: 0.1
      min_points_per_voxel: 1
      downsample_all_data: True
      filter_field_name: "x"
      filter_limit_min: -1
      filter_limit_max: 4.0
      negative: False
  - name: ExtractPlane
    type: point_cloud2_filters/SacSegmentationExtractFilterPointCloud2
    params:
      active: True
      input_frame: "wrist_camera_depth_optical_frame"
      output_frame: "wrist_camera_depth_optical_frame"
      model_type: 16                  # Detect planes (SACMODEL_PLANE)
      method_type: 0                  # Use RANSAC method
      axis_x: 0                       # Table is flat on the ground
      axis_y: 0
      axis_z: 1                       # Table is aligned along the Z-axis
      eps_angle: 0.1                  # Small tolerance for deviation
      distance_threshold: 0.01        # Smaller distance threshold for precision
      negative: False                 # Keep the table plane (set to True to remove the table)
      optimize_coefficents: True      # Optimize plane coefficients for better accuracy



```
I will appreciate any help.
Thanks in advance.

**Comment by torydebra** [comment]
Is this occuring in the initialization or while the chain is filtering actual data?
The example work for me (all the sensors are loaded correctly). 
If this is caused while filtering, could it be that the point cloud is empty? You can check the intermediate result of each filter of the chain setting its `pub_cloud` param to true

**Comment by vaibhavwalia921** [comment]
Thanks for the quick response.

I didn't tested it before with the pub_cloud. However I tested all the filters in Yaml individually. I get this this error while the following is included. 
```

 - name: ExtractPlane
    type: point_cloud2_filters/SacSegmentationExtractFilterPointCloud2
    params:
      active: True
      input_frame: "wrist_camera_depth_optical_frame"
      output_frame: "wrist_camera_depth_optical_frame"
      model_type: 16                  # Detect planes (SACMODEL_PLANE)
      method_type: 0                  # Use RANSAC method
      axis_x: 0                       # Table is flat on the ground
      axis_y: 0
      axis_z: 1                       # Table is aligned along the Z-axis
      eps_angle: 0.1                  # Small tolerance for deviation
      distance_threshold: 0.01        # Smaller distance threshold for precision
      negative: False                 # Keep the table plane (set to True to remove the table)
      optimize_coefficents: True      # Optimize plane coefficients for better accuracy
      
```
I actually used rqt_reconfigure to tune the params of every filter.
